name: CI
on:   
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    name: Mono
    runs-on: ubuntu-latest
    steps:
    #- uses: actions/checkout@v2
    #- name: setup-xamarin
    #  with:
    #    mono-version: 6.6 
    #- name: Build
    #  run: msbuild GalleryStoreManager


    
        