name: CI
on:   
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest

      
    steps:
    - uses: actions/checkout@v2
    - name: setup-xamarin
    - uses: actions/setup-mono@v1
      with:
        mono-version: 6.6 
    - name: Build
      run: msbuild GalleryStoreManager


    
        