name: CI
on: [push]
jobs:
  build:
    name: Mono
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup-xamarin    
#      uses: actions/Setup-MSBuild@v1
      with:
        mono-version: 6.6 # specify version in '<major>.<minor>' format    
    - name: test
      run: msbuild GalleryStoreManager


    
        